# Generated by Django 5.1.1 on 2024-11-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0003_bitcointransaction_reloadcard_ticket_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcointransaction',
            name='cryptomus_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bitcointransaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], max_length=50),
        ),
    ]
