# Generated by Django 5.1.1 on 2024-11-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0004_bitcointransaction_cryptomus_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitcointransaction',
            name='cryptomus_uuid',
        ),
    ]
