# Generated by Django 5.1.1 on 2024-11-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0007_remove_passenger_availablity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='card_id',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='famount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='recharge',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
