# Generated by Django 5.1.1 on 2024-11-25 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0011_admin_passenger_reg_passenger_reg_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitcointransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='support',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.RemoveField(
            model_name='reloadcard',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='BitcoinTransaction',
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
        migrations.DeleteModel(
            name='ReloadCard',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
