# Generated by Django 5.1.1 on 2024-11-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0012_remove_bitcointransaction_user_remove_creator_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_to', models.CharField(max_length=100)),
                ('c_from', models.CharField(max_length=100)),
            ],
        ),
    ]
