# Generated by Django 5.1.1 on 2024-11-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0013_children_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='children_form',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
