# Generated by Django 5.1.1 on 2024-11-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0015_childcard_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adults_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_to', models.CharField(max_length=100)),
                ('a_from', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdultsCard_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adultsName', models.CharField(max_length=100)),
                ('adultsAddress', models.CharField(max_length=150)),
                ('adultsMobile', models.CharField(max_length=15)),
            ],
        ),
    ]
