# Generated by Django 5.1.1 on 2024-11-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0017_cryptopayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='famount',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='recharge',
        ),
        migrations.AddField(
            model_name='passenger',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='p_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='p_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
