# Generated by Django 5.1.1 on 2024-11-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0018_remove_passenger_balance_remove_passenger_famount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('to_field', models.CharField(blank=True, max_length=100, null=True)),
                ('from_field', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
