# Generated by Django 5.1.1 on 2024-11-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator_app', '0019_combineddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
